version: '3'

services:
  react:
    image: react/tutorial:latest
    container_name: tutorial
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /root/practice-swing-react/
    command: ["bash"]
    ports:
      - 3000:3000
    networks:
      - tutorial-network
    volumes:
      - lspdatas:/root/.local/share/
      - practiceReact:/root/practice-swing-react/
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro

volumes:
  lspdatas:
  practiceReact:
networks:
  tutorial-network:
