version: '3'

services:
  react:
    image: react/tutorial:latest
    container_name: tutorial
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: ["npm", "start"]
    ports:
      - 3000:3000
    networks:
      - tutorial-network
    volumes:
      - ./src:/app/
      - lspdatas:/root/.local/share/

volumes:
  modules:
  lspdatas:
networks:
  tutorial-network:
